<h2>New content category</h2>

<div class="panel panel-default">
    <div class="panel-heading"><h4>Content Post</h4></div>
    <div class="panel-body">

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('content/category', array('action' => 'add')));
    $form->remove('content_category_id');
    $form->prepare();
    echo $this->renderFormHorizontal($form);
?>

    </div>
</div>