<?php $this->headScript()
           ->appendFile($this->basePath() . '/ckeditor/ckeditor.js');
?>
<h2>Edit content category</h2>

<div class="panel panel-default">
    <div class="panel-heading"><h4>Content Post</h4></div>
    <div class="panel-body">
    
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('content/category', array(
        'action' => 'edit',
        'categoryid' => $this->id
    )));
    $form->prepare();
    echo $this->renderFormVertical($form, '');
?>

    </div>
</div>