<ol class="breadcrumb">
  <li class="active">Content Categories</li>
</ol>

<h2>Content Categories</h2>
<table  class="table table-striped">
    <tr>
      <th>Category Name</th>
      <th>Actions</th>
    </tr>
    <?php foreach($this->categories as $category):?>
    <tr>
        <td>
            <a href="<?php echo $this->url('content/list', array(
                'category' => $category->getUrlPath()
            )); ?>"><?php echo $category->getCategoryName()?></a>
        </td>
        <td>
            <a href="<?php echo $this->url('content/category', array(
                'action' => 'edit',
                'categoryid'   => $category->getContentCategoryId()
            )); ?>">Edit</a>
            <a href="<?php echo $this->url('content/category', array(
                'action' => 'delete',
                'categoryid'   => $category->getContentCategoryId()
            )); ?>">Delete</a>
            <a href="<?php echo $this->url('civ-content', array(
                'category'   => $category->getUrlPath()
            )); ?>">Preview</a>
        </td>
    </tr>
    <?php endforeach;?>
</table>

<a class="btn btn-default" href="<?php echo $this->url('content/category', array(
    'action' => 'add'
))?>">Add new category</a>