<h2>Content Categories</h2>
<table  class="table table-striped">
    <tr>
      <th>Category Name</th>
      <th>Actions</th>
    </tr>
    <?php foreach($this->categories as $category):?>
    <tr>
        <td>
            <?php echo $category->getCategoryName()?>
        </td>
        <td>
            <a href="<?php echo $this->url('content/category', array(
                'action' => 'edit',
                'categoryid'   => $category->getContentCategoryId()
            )); ?>">Edit</a>
            <a href="<?php echo $this->url('content/category', array(
                'action' => 'delete',
                'categoryid'   => $category->getContentCategoryId()
            )); ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach;?>
</table>

<a class="btn btn-default" href="<?php echo $this->url('content/category', array(
    'action' => 'add'
))?>">Add new category</a>

<a class="btn btn-default" href="<?php echo $this->url('content/action', array(
    'action' => 'index'
))?>">Content Posts</a>