<?php $this->headScript()
           ->appendFile($this->basePath() . '/ckeditor/ckeditor.js');
?>
<h2>Edit content post</h2>

<div class="panel panel-default">
    <div class="panel-heading"><h4>Content Post</h4></div>
    <div class="panel-body">
  
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('content/action', array(
        'action' => 'edit',
        'postid' => $this->post->getContentPostId()
    )));
    $form->prepare();
    echo $this->renderFormHorizontal($form);
?>

    </div>
</div>