<h1>Content Posts</h1>
<table  class="table table-striped">
    <tr>
      <th>Post Title</th>
      <th>Actions</th>
    </tr>
    <?php foreach($this->posts as $post):?>
    <tr>
        <td>
            <a href="<?php echo $this->url('civ-content', array(
                'category' => 'asas',
                'postid'   => $post->getContentPostId()
            )); ?>"><?php echo $post->getPostTitle()?></a>
        </td>
        <td>
            <a href="<?php echo $this->url('content/action', array(
                'action' => 'edit',
                'postid'   => $post->getContentPostId()
            )); ?>">Edit</a>
            <a href="<?php echo $this->url('content/action', array(
                'action' => 'delete',
                'postid'   => $post->getContentPostId()
            )); ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach;?>
</table>