<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('content/category', array(
          'action' => 'index'
      )); ?>">Content Categories</a></li>
  <li class="active"><?php echo $this->category->getCategoryName(); ?></li>
</ol>

<h2><?php echo $this->category->getCategoryName(); ?> Posts</h2>
<table  class="table table-striped">
    <tr>
      <th>Post Title</th>
      <th>Actions</th>
    </tr>
    <?php foreach($this->posts as $post):?>
    <tr>
        <td>
            <a href="<?php echo $this->url('civ-content/post', array(
                'category' => 'asas',
                'postid'   => $post->getContentPostId()
            )); ?>"><?php echo $post->getPostTitle()?></a>
        </td>
        <td>
            <a href="<?php echo $this->url('content/action', array(
                'action' => 'edit',
                'postid'   => $post->getContentPostId()
            )); ?>">Edit</a>
            <a href="<?php echo $this->url('content/action', array(
                'action' => 'delete',
                'postid'   => $post->getContentPostId()
            )); ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach;?>
</table>

<a class="btn btn-default" href="<?php echo $this->url('content/action', array(
    'action' => 'add'
)); ?>">New Post</a>