<?php $this->headScript()
           ->appendFile($this->basePath() . '/ckeditor/ckeditor.js');
?>
<h1>Hello world!</h1>

<form>
    <textarea name="editor1" id="editor1" rows="10" cols="80">
        This is my textarea to be replaced with CKEditor.
    </textarea>
    <script>
        CKEDITOR.replace('editor1', {
        	toolbarGroups : [
        	                        { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
        	                        { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
        	                        { name: 'links' },
        	                        { name: 'insert' },
        	                        { name: 'forms' },
        	                        { name: 'tools' },
        	                        { name: 'document',    groups: [ 'mode', 'document', 'doctools' ] },
        	                        { name: 'others' },
        	                        '/',
        	                        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
        	                        { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align' ] },
        	                        { name: 'styles' },
        	                        { name: 'colors' },
        	                 //       { name: 'about' }
        	                    ]
            
        });
    </script>
</form>